Consistent allocation
genaray/ZeroAllocJobScheduler pull request #15
Opened 2023-10-13 08:55 UTC by LilithSilver

Closes #11 and #10

Adds the ability to configure `JobScheduler` to start with a maximum number of concurrent job slots to frontload allocation/garbage creation, and an optional strict mode that will throw if those slots are exceeded.

Adds some additional benchmarks and testing, and revises what was already there to be more accurate.

2023-10-13 15:27 UTC, genaray requested changes
Thanks! Looks good so far, just a few small side notes :)

2023-10-13 15:27 UTC, genaray commented on JobScheduler/JobHandle.cs
> +    public static void CompleteAll(List<JobHandle> handles)
Everything is fine here, but it just occurred to me that in the future we should perhaps also offer a span overload for all operations.

2023-10-13 15:27 UTC, genaray commented on JobScheduler/JobPool.cs
> +    private int _nextId;
I would still call this size, but I thought it was clearer because it is about the "size" of the pool. How much is occupied, so to speak.

2023-10-13 15:27 UTC, genaray commented on JobScheduler/JobPool.cs
> +    private Job?[] _jobs;
Would remove the ? and accordingly all optionals. In the end, an optional is a class and if we do not want one thing then they are classes. Also I find that this .Value behind each access is also somehow unclean, harder to read ^^

2023-10-13 15:27 UTC, genaray commented on JobScheduler/JobPool.cs
> +        JobId id;
```csharp
var recycle = _recycledIds.TryDequeue(out var recycledId);
var recycled = recycle ? recycledId : new JobId(_size, 1);
```
Would keep the top one, I find it a bit cleaner. But is only my personal style ^^

2023-10-13 15:27 UTC, genaray commented on JobScheduler/JobPool.cs
> +        return !job.HasValue || // if it's missing, we've completed and removed it, and its ID hasn't been reused yet
Back to `== -1` when we remove optionals.

2023-10-13 15:27 UTC, genaray commented on JobScheduler/JobScheduler.cs
> +
normal attributes above the constructor, properties directly below. Thus the code-style is kept which also exists in arch ^^

2023-10-13 17:09 UTC, LilithSilver commented on JobScheduler/JobPool.cs
> +    private int _nextId;
Hmm, I renamed it because I didn't want it to be confused with JobCount. Maybe _currentMaxSize?

2023-10-13 17:17 UTC, LilithSilver commented on JobScheduler/JobPool.cs
> +    private Job?[] _jobs;
Will do, for style! I will say, though, that an optional struct is still a struct. That's why they need the `.Value` calls. It just acts as a bool field wrapper around the struct, basically. 

The reason I added them in the first place was to prevent a nullable `ManualResetEvent?` on the `Job`, because we need to either set the overall nullable to null or set that to null when the job in the array gets completed. So I'll instead use the nullable on the event, if that works for you?

2023-10-13 17:24 UTC, LilithSilver commented on JobScheduler/JobPool.cs
> +        JobId id;
There was a bug before with the ID increasing without bound, after a ton of recycles, hitting the tens of thousands sometimes and eventually causing an array access error if something then goes over the expected count. That's why _nextId++ needs to be in the brackets.

How does this seem as a better option though?

```
if (!_recycledIds.TryDequeue(out var id))
        {
            id = new JobId(_nextId, 1);
            _nextId++;
        }
```

2023-10-15 14:54 UTC, genaray approved these changes

2023-10-15 14:54 UTC, merged

2023-10-15 14:55 UTC, genaray commented
Thanks! Looking great! :)